name: sunmiv2printtest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sunmi_printer_plus: any
  xml: any
  image: ^4.0.0
  permission_handler: ^12.0.3
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true

  assets:
    - assets/